# Generated by Django 2.0.4 on 2018-04-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0002_event_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_description',
            field=models.CharField(default='', max_length=750),
        ),
    ]
