# Generated by Django 2.0.4 on 2018-04-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0003_auto_20180417_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(default='', max_length=750),
        ),
        migrations.AddField(
            model_name='event',
            name='picture_url',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
