# Generated by Django 2.0.4 on 2018-04-17 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0004_auto_20180417_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organization',
        ),
    ]
